[package]
name = "blip-cli"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "contexts", "js_runner", "json_converter", "mirror", "types" ]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
types = { path = "./types" }
contexts = { path = "./contexts" }
