[package]
name = "blip-cli"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "flow_parser", "types" ]

[dependencies]
deno_core = "0.341.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
types = { path = "./types" }
flow_parser = { path = "./flow_parser" }