[package]
name = "mirror"
version = "0.1.0"
edition = "2024"

[dependencies]
http = { path = "../http" }
ui = { path = "../ui" }
file_handler = { path = "../file_handler" } 
domain = { path = "../domain" }
serde_json = "1.0.140"