[package]
name = "file_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
ui = { path = "../ui" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"